// <auto-generated />
using BrainBoostBreak.Server;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace BrainBoostBreak.Server.Migrations
{
    [DbContext(typeof(QuestionDatabase))]
    [Migration("20190814123635_newquestions")]
    partial class newquestions
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "3.0.0-preview5.19227.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("BrainBoostBreak.Server.Answer", b =>
                {
                    b.Property<int>("AnswerId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AnswerDescription");

                    b.Property<string>("Text")
                        .IsRequired();

                    b.Property<int>("TopicId");

                    b.Property<string>("Url");

                    b.HasKey("AnswerId");

                    b.HasIndex("TopicId");

                    b.ToTable("Answers");

                    b.HasData(
                        new
                        {
                            AnswerId = 1,
                            Text = "Sokrates",
                            TopicId = -1
                        },
                        new
                        {
                            AnswerId = 2,
                            Text = "Platon",
                            TopicId = -1
                        },
                        new
                        {
                            AnswerId = 3,
                            Text = "Friedrich Nietzsche",
                            TopicId = -1
                        },
                        new
                        {
                            AnswerId = 4,
                            Text = "Paracelsus",
                            TopicId = -1
                        },
                        new
                        {
                            AnswerId = 5,
                            Text = "Erasmus von Rotterdam",
                            TopicId = -1
                        },
                        new
                        {
                            AnswerId = 6,
                            Text = "Baruch de Spinoza",
                            TopicId = -1
                        },
                        new
                        {
                            AnswerId = 7,
                            Text = "Mahatma Gandhi",
                            TopicId = -1
                        },
                        new
                        {
                            AnswerId = 8,
                            Text = "Fidel Castro",
                            TopicId = -1
                        },
                        new
                        {
                            AnswerId = 9,
                            Text = "Sokrates",
                            TopicId = -1
                        },
                        new
                        {
                            AnswerId = 10,
                            Text = "Platon",
                            TopicId = -1
                        },
                        new
                        {
                            AnswerId = 11,
                            Text = "Friedrich Nietzsche",
                            TopicId = -1
                        },
                        new
                        {
                            AnswerId = 12,
                            Text = "Paracelsus",
                            TopicId = -1
                        },
                        new
                        {
                            AnswerId = 13,
                            Text = "Jean-Jacques Rousseau",
                            TopicId = -1
                        },
                        new
                        {
                            AnswerId = 14,
                            Text = "Fidel Castro",
                            TopicId = -1
                        },
                        new
                        {
                            AnswerId = 15,
                            Text = "Sokrates",
                            TopicId = -1
                        },
                        new
                        {
                            AnswerId = 16,
                            Text = "Platon",
                            TopicId = -1
                        },
                        new
                        {
                            AnswerId = 17,
                            Text = "Friedrich Nietzsche",
                            TopicId = -1
                        },
                        new
                        {
                            AnswerId = 18,
                            Text = "Paracelsus",
                            TopicId = -1
                        },
                        new
                        {
                            AnswerId = 19,
                            Text = "Siddhartha Gautama",
                            TopicId = -1
                        },
                        new
                        {
                            AnswerId = 20,
                            Text = "Fidel Castro",
                            TopicId = -1
                        },
                        new
                        {
                            AnswerId = 21,
                            Text = "Sokrates",
                            TopicId = -1
                        },
                        new
                        {
                            AnswerId = 22,
                            Text = "Platon",
                            TopicId = -1
                        },
                        new
                        {
                            AnswerId = 23,
                            Text = "Friedrich Nietzsche",
                            TopicId = -1
                        },
                        new
                        {
                            AnswerId = 24,
                            Text = "Paracelsus",
                            TopicId = -1
                        },
                        new
                        {
                            AnswerId = 25,
                            Text = "Theodor Fontane",
                            TopicId = -1
                        },
                        new
                        {
                            AnswerId = 26,
                            Text = "Fidel Castro",
                            TopicId = -1
                        },
                        new
                        {
                            AnswerId = 27,
                            Text = "Sokrates",
                            TopicId = -1
                        },
                        new
                        {
                            AnswerId = 28,
                            Text = "Platon",
                            TopicId = -1
                        },
                        new
                        {
                            AnswerId = 29,
                            Text = "Friedrich Nietzsche",
                            TopicId = -1
                        },
                        new
                        {
                            AnswerId = 30,
                            Text = "Paracelsus",
                            TopicId = -1
                        },
                        new
                        {
                            AnswerId = 31,
                            Text = "a",
                            TopicId = -2
                        },
                        new
                        {
                            AnswerId = 32,
                            Text = "b",
                            TopicId = -2
                        },
                        new
                        {
                            AnswerId = 33,
                            Text = "c",
                            TopicId = -2
                        },
                        new
                        {
                            AnswerId = 34,
                            Text = "d",
                            TopicId = -2
                        },
                        new
                        {
                            AnswerId = 35,
                            Text = "e",
                            TopicId = -2
                        },
                        new
                        {
                            AnswerId = 36,
                            Text = "f",
                            TopicId = -2
                        },
                        new
                        {
                            AnswerId = 37,
                            Text = "g",
                            TopicId = -2
                        },
                        new
                        {
                            AnswerId = 38,
                            Text = "h",
                            TopicId = -2
                        },
                        new
                        {
                            AnswerId = 39,
                            Text = "i",
                            TopicId = -2
                        },
                        new
                        {
                            AnswerId = 40,
                            Text = "j",
                            TopicId = -2
                        },
                        new
                        {
                            AnswerId = 41,
                            Text = "k",
                            TopicId = -2
                        },
                        new
                        {
                            AnswerId = 42,
                            Text = "l",
                            TopicId = -2
                        },
                        new
                        {
                            AnswerId = 43,
                            Text = "m",
                            TopicId = -2
                        },
                        new
                        {
                            AnswerId = 44,
                            Text = "n",
                            TopicId = -2
                        },
                        new
                        {
                            AnswerId = 45,
                            Text = "o",
                            TopicId = -2
                        },
                        new
                        {
                            AnswerId = 46,
                            Text = "p",
                            TopicId = -2
                        },
                        new
                        {
                            AnswerId = 47,
                            Text = "q",
                            TopicId = -2
                        },
                        new
                        {
                            AnswerId = 48,
                            Text = "r",
                            TopicId = -2
                        },
                        new
                        {
                            AnswerId = 49,
                            Text = "s",
                            TopicId = -2
                        },
                        new
                        {
                            AnswerId = 50,
                            Text = "t",
                            TopicId = -2
                        },
                        new
                        {
                            AnswerId = 51,
                            Text = "u",
                            TopicId = -2
                        },
                        new
                        {
                            AnswerId = 52,
                            Text = "v",
                            TopicId = -2
                        },
                        new
                        {
                            AnswerId = 53,
                            Text = "w",
                            TopicId = -2
                        },
                        new
                        {
                            AnswerId = 54,
                            Text = "x",
                            TopicId = -2
                        },
                        new
                        {
                            AnswerId = 55,
                            Text = "y",
                            TopicId = -2
                        },
                        new
                        {
                            AnswerId = 56,
                            Text = "z",
                            TopicId = -2
                        },
                        new
                        {
                            AnswerId = 57,
                            Text = "ä",
                            TopicId = -2
                        },
                        new
                        {
                            AnswerId = 58,
                            Text = "ü",
                            TopicId = -2
                        },
                        new
                        {
                            AnswerId = 59,
                            Text = "ö",
                            TopicId = -2
                        });
                });

            modelBuilder.Entity("BrainBoostBreak.Server.Question", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AnswerId");

                    b.Property<string>("Text")
                        .IsRequired();

                    b.Property<int>("TopicId");

                    b.HasKey("QuestionId");

                    b.HasIndex("AnswerId");

                    b.HasIndex("TopicId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            QuestionId = 1,
                            AnswerId = 1,
                            Text = "Wem wird folgendes Zitat zugeschrieben: 'Wer glaubt, etwas zu sein, hat aufgehört, etwas zu werden.'",
                            TopicId = -1
                        },
                        new
                        {
                            QuestionId = 2,
                            AnswerId = 7,
                            Text = "Wem wird folgendes Zitat zugeschrieben: 'Gewalt ist die Waffe des Schwachen.'",
                            TopicId = -1
                        },
                        new
                        {
                            QuestionId = 3,
                            AnswerId = 13,
                            Text = "Wem wird folgendes Zitat zugeschrieben: 'Das Geld, das man besitzt, ist das Mittel zur Freiheit, dasjenige, dem man nachjagt, das Mittel zur Knechtschaft.'",
                            TopicId = -1
                        },
                        new
                        {
                            QuestionId = 4,
                            AnswerId = 19,
                            Text = "Wem wird folgendes Zitat zugeschrieben: 'Wir sind, was wir denken. Alles, was wir sind, entsteht aus unseren Gedanken. Mit unseren Gedanken formen wir die Welt.'",
                            TopicId = -1
                        },
                        new
                        {
                            QuestionId = 5,
                            AnswerId = 25,
                            Text = "Wem wird folgendes Zitat zugeschrieben: 'Gegen eine Dummheit, die gerade in Mode ist, kommt keine Klugheit auf.'",
                            TopicId = -1
                        },
                        new
                        {
                            QuestionId = 6,
                            AnswerId = 31,
                            Text = "A",
                            TopicId = -2
                        },
                        new
                        {
                            QuestionId = 7,
                            AnswerId = 32,
                            Text = "B",
                            TopicId = -2
                        },
                        new
                        {
                            QuestionId = 8,
                            AnswerId = 33,
                            Text = "C",
                            TopicId = -2
                        },
                        new
                        {
                            QuestionId = 9,
                            AnswerId = 34,
                            Text = "D",
                            TopicId = -2
                        },
                        new
                        {
                            QuestionId = 10,
                            AnswerId = 35,
                            Text = "E",
                            TopicId = -2
                        },
                        new
                        {
                            QuestionId = 11,
                            AnswerId = 36,
                            Text = "F",
                            TopicId = -2
                        },
                        new
                        {
                            QuestionId = 12,
                            AnswerId = 37,
                            Text = "G",
                            TopicId = -2
                        },
                        new
                        {
                            QuestionId = 13,
                            AnswerId = 38,
                            Text = "H",
                            TopicId = -2
                        },
                        new
                        {
                            QuestionId = 14,
                            AnswerId = 39,
                            Text = "I",
                            TopicId = -2
                        },
                        new
                        {
                            QuestionId = 15,
                            AnswerId = 40,
                            Text = "J",
                            TopicId = -2
                        },
                        new
                        {
                            QuestionId = 16,
                            AnswerId = 41,
                            Text = "K",
                            TopicId = -2
                        },
                        new
                        {
                            QuestionId = 17,
                            AnswerId = 42,
                            Text = "L",
                            TopicId = -2
                        },
                        new
                        {
                            QuestionId = 18,
                            AnswerId = 43,
                            Text = "M",
                            TopicId = -2
                        },
                        new
                        {
                            QuestionId = 19,
                            AnswerId = 44,
                            Text = "N",
                            TopicId = -2
                        },
                        new
                        {
                            QuestionId = 20,
                            AnswerId = 45,
                            Text = "O",
                            TopicId = -2
                        },
                        new
                        {
                            QuestionId = 21,
                            AnswerId = 46,
                            Text = "P",
                            TopicId = -2
                        },
                        new
                        {
                            QuestionId = 22,
                            AnswerId = 47,
                            Text = "Q",
                            TopicId = -2
                        },
                        new
                        {
                            QuestionId = 23,
                            AnswerId = 48,
                            Text = "R",
                            TopicId = -2
                        },
                        new
                        {
                            QuestionId = 24,
                            AnswerId = 49,
                            Text = "S",
                            TopicId = -2
                        },
                        new
                        {
                            QuestionId = 25,
                            AnswerId = 50,
                            Text = "T",
                            TopicId = -2
                        },
                        new
                        {
                            QuestionId = 26,
                            AnswerId = 51,
                            Text = "U",
                            TopicId = -2
                        },
                        new
                        {
                            QuestionId = 27,
                            AnswerId = 52,
                            Text = "V",
                            TopicId = -2
                        },
                        new
                        {
                            QuestionId = 28,
                            AnswerId = 53,
                            Text = "W",
                            TopicId = -2
                        },
                        new
                        {
                            QuestionId = 29,
                            AnswerId = 54,
                            Text = "X",
                            TopicId = -2
                        },
                        new
                        {
                            QuestionId = 30,
                            AnswerId = 55,
                            Text = "Y",
                            TopicId = -2
                        },
                        new
                        {
                            QuestionId = 31,
                            AnswerId = 56,
                            Text = "Z",
                            TopicId = -2
                        },
                        new
                        {
                            QuestionId = 32,
                            AnswerId = 57,
                            Text = "Ä",
                            TopicId = -2
                        },
                        new
                        {
                            QuestionId = 33,
                            AnswerId = 58,
                            Text = "Ü",
                            TopicId = -2
                        },
                        new
                        {
                            QuestionId = 34,
                            AnswerId = 59,
                            Text = "Ö",
                            TopicId = -2
                        });
                });

            modelBuilder.Entity("BrainBoostBreak.Server.Topic", b =>
                {
                    b.Property<int>("TopicId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("TopicId");

                    b.ToTable("Topics");

                    b.HasData(
                        new
                        {
                            TopicId = -1,
                            Name = "Zitate"
                        },
                        new
                        {
                            TopicId = -2,
                            Name = "Buchstaben lernen"
                        });
                });

            modelBuilder.Entity("BrainBoostBreak.Server.Answer", b =>
                {
                    b.HasOne("BrainBoostBreak.Server.Topic", "Topic")
                        .WithMany()
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BrainBoostBreak.Server.Question", b =>
                {
                    b.HasOne("BrainBoostBreak.Server.Answer", "Answer")
                        .WithMany()
                        .HasForeignKey("AnswerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BrainBoostBreak.Server.Topic", "Topic")
                        .WithMany()
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
